# Generated by Django 4.2.3 on 2023-07-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_cart_user_cart_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_variant',
            new_name='product_size',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
