# Generated by Django 4.2.3 on 2023-07-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
    ]
